version: "3.5"

services:
  selenium-hub:
    image: selenium/hub:4.8.1-20230221
    container_name: selenium-hub
    ports:
      # descomentar para conectar nodes externos
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  firefox:
    image: selenium/node-firefox:4.8.1-20230221
    container_name: node-firefox
    shm_size: 1gb
    env_file:
      - .env
    volumes:
      - ./shared/firefox:/home/seluser/Downloads
    depends_on:
      - selenium-hub

  chrome:
    image: selenium/node-chrome:4.8.1-20230221
    container_name: node-chrome
    shm_size: 1gb
    env_file:
      - .env
    volumes:
      - ./shared/chrome:/home/seluser/Downloads
    depends_on:
      - selenium-hub
